### ISSUE TITLE
systemd service units and timer

### ISSUE THREAD

**Issue by stef204** [MarkHedleyJones/dmenu-extended#53] opened 2017-09-21 02:16 UTC
@markjones112358 
Are you sure your service units and timer are written correctly?  They do not seem to work for me.

On my system, path to file is /usr/bin/dmenu_extended_cache_build, so I tried to use the system service unit, with `systemsctl --user start update-dmenu-extended-db.system.service`

Fails with various iterations of:  `Invalid user/group name or numeric ID:`

Timer will not load since unit does not.

Are these working for you?

Edit: removing the line `"User=%i"` seems to do the trick (for the user unit).
I am either using the systemd-install.sh script wrong or it fails to insert the user name instead of `%i` in the unit file.

(In addition, I am not sure specifying the user is necessary in this case.)

But will look further into it and probably write my own service and timer files.

**Comment by markjones112358** [comment] 2017-09-24 05:59
Hi,
Sorry, but I have no idea how these systemd services work. And no, my systemd service isn't working.
This integration was an outside contribution and at the time I merged it I thought it worked.
Sorry I can't be more help, systemd is not something I've become familiar with.
If you find a way to get these service files working, create a merge request and I'll integrate them into dmenu-extended.

**Comment by stef204** [comment] 2017-09-26 14:41
Thanks for your feedback. I have it working now.  I just want to make sure the files are written in the best manner possible and once that is done and will create a pull request.

**Comment by markjones112358** [comment] 2017-09-27 04:58
Great, I look forward to integrating your changes.

**Comment by nanobecquerel** [comment] 2018-01-20 06:30
The problem is that the path to the dmenu_extended_cache_build script is hard-coded into the systemd unit files. If the setup.py installer is used for dmenu-extended, these paths are correct; if the user manually installs dmenu-extended elsewhere then they are wrong.
I will open a pull request shortly with a possible fix.

**Comment by MarkHedleyJones** [comment] 2018-02-17 04:56
Hi again.
I've modified your systemd install script slightly so as to improve auto-detection of the dmenu_extended_cache_build script (default location on my machine differs from what was hard-coded into the script). If you get a chance, could you confirm that it's still working as you intended. I've added your name to the contributions at the bottom of the README too.

**Closed** 2018-10-09 00:16 UTC
